import { BadgeCheckIcon, ChartNoAxesCombinedIcon, Lightbulb } from "lucide-react";

const features = [
    {
        title: "AI-Powered Questions",
        description:
            "Get role-specific questions generated by advanced AI models.",
        icon: Lightbulb
    },
    {
        title: "Instant Feedback",
        description:
            "Receive detailed analysis and scores across multiple skill areas instantly.",
        icon: ChartNoAxesCombinedIcon
    },
    {
        title: "Core Strengths & Focus Areas",
        description:
            "Discover your core strengths and focus areas with detailed AI-powered insights after every interview.",
        icon: BadgeCheckIcon
    },
];

const Features = () => {
    return (
        <section
            id="features"
            className="bg-gray-50 py-24 text-gray-900 border-b border-gray-200"
        >
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

                {/* Section Heading */}
                <div className="text-center mb-16">
                    <h2 className="text-3xl md:text-4xl font-bold mb-4">
                        Everything You Need to <span className="text-[#006c49]">Ace Your Interview</span>
                    </h2>
                </div>

                {/* Feature Cards */}
                <div className="grid md:grid-cols-3 gap-8">

                    {features.map((feature) => (
                        <div
                            key={feature.title}
                            className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 flex flex-col items-start gap-4"
                        >
                            {/* Icon */}
                            <div className="w-12 h-12 rounded-full bg-emerald-50 text-[#006c49] flex items-center justify-center shrink-0">
                                <feature.icon/>
                            </div>

                            {/* Content */}
                            <div>
                                <h3 className="text-xl font-bold mb-2">
                                    {feature.title}
                                </h3>

                                <p className="text-gray-600">
                                    {feature.description}
                                </p>
                            </div>
                        </div>
                    ))}

                </div>
            </div>
        </section>
    );
};

export default Features;